name: express_cars_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-334.2.beta

# Add regular dependencies here.
dependencies:
  hive: ^2.2.3
  shelf: ^1.4.0
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1